RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
cccccccccccccccccccccccccccccccccccccccc
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
gggggggggggggggggggggggggggggggggggggggg
